### ISSUE TITLE
Change the header?

### ISSUE THREAD

**Issue by sector-f** [sudokode/pbwww#13]
Since this is "official" now, perhaps the word "shit" should be changed? Or we can just not give a fuck.

Oh, and can we get the link on the main page changed to end in .html?

**Comment by buhman** [comment]
> Or we can just not give a fuck.

This.

> link on the main page changed to end in .html?

[That](https://github.com/sudokode/pbwww/pull/14).

**Comment by sudokode** [comment]
Agreed.
